tasks:
  - init: pip install -r requirements.txt
  - name: Startup
    command: echo Exporting ${GITPOD_REPO_ROOT#*"ace/"}
    env:
      REPONAME: ${GITPOD_REPO_ROOT#*"ace/"}

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
