tasks:
  - init: pip install -r requirements.txt
  - name: Startup
    command: eval $(gp env -e REPONAME=${GITPOD_REPO_ROOT#*"ace/"})

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
